---
version: "2.1"
services:
  frontail:
    image: welteki/frontail-openhab:latest
    container_name: "frontail"
    #    healthcheck:
    #      test: ["CMD", "curl", "-sI", "http://127.0.0.1:8086/ping"]
    #      interval: 30s
    #      timeout: 1s
    #      retries: 24
    environment:
      - TZ=${TZ}
    networks:
      - t2_proxy
    ports:
      - 9009:9001
    restart: unless-stopped
    volumes:
        - ${DATADIR}/openhab/userdata/logs:/var/log/openhab:ro
networks:
  t2_proxy:
    external: true

