# Create netxcloud network first
# docker network create nextcloud
#NOTES:
#1. certificatesresolvers.myresolver.acme.email=myemail@gmail.com
#2. TRUSTED_PROXIES values based on your 'traefik docker network run docker network inspect traefik' to see the network
#3. remove traefik.http.middlewares.nextcloud.headers.contentSecurityPolicy and
#traefik.http.middlewares.nextcloud.headers.customFrameOptionsValue if you don't want to allow iframe your domain


version: '3.3'

services:

  db:
    restart: always
    image: postgres:11
    container_name: nextcloud-db
    networks:
      - nextcloud
    environment:
    - POSTGRES_USER=nextcloud
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=nextcloud
    volumes:
    - ${DATADIR}/nextcloud/db:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: nextcloud-redis
    restart: always
    networks:
      - nextcloud
    volumes:
      - ${DATADIR}/nextcloud/redis:/var/lib/redis

  nextcloud:
    image: nextcloud:stable
    container_name: nextcloud
    restart: always
    networks:
      - t2_proxy
      - nextcloud
    depends_on:
      - redis
      - db
    labels:
      - traefik.enable=true
      - traefik.http.routers.nextcloud.middlewares=nextcloud,nextcloud-caldav
      - traefik.http.routers.nextcloud.tls.certresolver=default
      - traefik.http.routers.nextcloud.rule=Host(`nextcloud.eisvogelweg2.de`)
      - traefik.http.middlewares.nextcloud.headers.customFrameOptionsValue=SAMEORIGIN
      - traefik.http.middlewares.nextcloud.headers.contentSecurityPolicy=frame-ancestors 'self' eisvogelweg2.de *.eisvogelweg2.de
      - traefik.http.middlewares.nextcloud.headers.stsSeconds=155520011
      - traefik.http.middlewares.nextcloud.headers.stsIncludeSubdomains=true
      - traefik.http.middlewares.nextcloud.headers.stsPreload=true
        #      - traefik.http.middlewares.nextcloud_redirect.redirectregex.regex=/.well-known/(card|cal)dav
        #      - traefik.http.middlewares.nextcloud_redirect.redirectregex.replacement=/remote.php/dav/
      - traefik.http.middlewares.nextcloud-caldav.redirectregex.permanent=true
      - traefik.http.middlewares.nextcloud-caldav.redirectregex.regex=^https://(.*)/.well-known/(card|cal)dav
      - traefik.http.middlewares.nextcloud-caldav.redirectregex.replacement=https://$${1}/remote.php/dav/
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=adminpass
      - REDIS_HOST=redis
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.eisvogelweg2.de
      - TRUSTED_PROXIES=192.168.90.0/24
    volumes:
      - ${DATADIR}/nextcloud/www:/var/www/html
      - /mnt/nasgard/nextcloud:/var/www/html/data

networks:
  t2_proxy:
    external: true

  nextcloud:
    external: true

