version: "3.3"
services:

# NGINX as Webserver for www.honkhausen.de
  www-site2:
    container_name: www.honkhausen.de
    restart: unless-stopped
    image: linuxserver/nginx
    volumes:
      - ${DATADIR}/www.honkhausen.de/config:/config
#    ports:
#      - 1080:80
#      - 1443:443
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - t2_proxy
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.honkhausen-rtr.entrypoints=https"
      - "traefik.http.routers.honkhausen-rtr.rule=Host(`www.honkhausen.de`)"
      - "traefik.http.routers.honkhausen-rtr.tls=true"
#      - "traefik.http.routers.honkhausen-rtr.tls.certresolver=dns-cloudflare"
      ## Middlewares
      - "traefik.http.routers.honkhausen-rtr.middlewares=chain-no-auth@file" # No Authentication
#      - "traefik.http.routers.honkhausen-rtr.middlewares=chain-basic-auth@file" # Basic Authentication
#      - "traefik.http.routers.honkhausen-rtr.middlewares=chain-oauth@file" # Google OAuth 2.0
      ## HTTP Services
      - "traefik.http.routers.honkhausen-rtr.service=honkhausen-svc"
      - "traefik.http.services.honkhausen-svc.loadbalancer.server.port=80"

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://www.honkhausen.de || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 5

networks:
  t2_proxy:
    external: true
 
