version: "3.3"
services:

# NGINX as Webserver for www.honkhausen.de
  nginx-hh:
    container_name: nginx-hh
    restart: unless-stopped
    image: linuxserver/nginx
    volumes:
      - ${USERDIR}/docker/nginx-hh/config:/config
    expose:
      - 80
#    ports:
#      - 1080:80
#      - 1443:443
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VIRTUAL_HOST=www.honkhausen.de
      - LETSENCRYPT_HOST=www.honkhausen.de
      - LETSENCRYPT_EMAIL=eddie.faf@googlemail.com

networks:
  default:
    external:
      name: nginx-proxy

