version: "3.3"
services:

# OpenVPN Server
  openvpn:
    image: kylemanna/openvpn
    container_name: openvpn
    privileged: true
    cap_add:
      - NET_ADMIN
    ports:
      - "1194:1194/udp"
    expose:
      - 1194
    restart: unless-stopped
    volumes:
      - ${DATADIR}/openvpn/config:/etc/openvpn
    devices:
      - /dev/net/tun
    environment:
#      - VIRTUAL_PORT=1194
      - VIRTUAL_HOST=vpn.${DOMAINNAME}
      - LETSENCRYPT_HOST=vpn.${DOMAINNAME}
      - LETSENCRYPT_EMAIL=eddie.faf@googlemail.com

networks:
  default:
    external:
      name: nginx-proxy

