### Nextcloud
### docker-compose.yml
###
###
##START
version: '3'
services:

 nextcloud:
  image: nextcloud-php74-apache:18.0.3
  container_name: nextcloud
  restart: always
  networks:
   - intern
   - t2_proxy
  ports:
   - 80
  environment:
   MYSQL_HOST: mariadbmaster:3306
   MYSQL_PASSWORD: ${DB_PASSWORD}
   MYSQL_DATABASE: ${DB_NAME}
   MYSQL_USER: ${DB_USER}
   REDIS_HOST: redis-app
   REDIS_HOST_PASSWORD: 9f1297a5793ed18422d3ec92a0eb23d9d91e68d7524937af6248d0ed6b6d006f
  labels:
    - "traefik.enable=true"
    - "traefik.docker.network=t2_proxy"
    ## TCP Routers
    - "traefik.tcp.routers.nextcloud-tcp.entrypoints=https"
    - "traefik.tcp.routers.nextcloud-tcp.rule=HostSNI(`nextcloud.$DOMAINNAME`)"
    - "traefik.tcp.routers.nextcloud-tcp.tls=true"
    - "traefik.tcp.routers.nextcloud-tcp.tls.certresolver=dns-cloudflare"
    - "traefik.tcp.routers.nextcloud-tcp.tls.passthrough=true"
    ## TCP Services
    - "traefik.tcp.routers.nextcloud-tcp.service=nextcloud-tcp-svc"
    - "traefik.tcp.services.nextcloud-tcp-svc.loadbalancer.server.port=443"
  volumes:
   - /media/t1/nextclouddata:/var/www/html/data
   - ${DATADIR}/nextcloud/wwwdata:/var/www/html
  external_links:
   - mariadbmaster
   - redis-app

networks:
  intern:
    external: true
  t2_proxy:
    external: true
##EOF
