### Nextcloud
### docker-compose.yml
###
###
##START
version: '3'
services:

 nextcloud:
  image: nextcloud-php74-apache:latest
  container_name: nextcloud
  restart: always
  networks:
   - intern
   - t2_proxy
  ports:
   - 80
  environment:
   MYSQL_HOST: mariadbmaster:3306
   MYSQL_PASSWORD: ${DB_PASSWORD}
   MYSQL_DATABASE: ${DB_NAME}
   MYSQL_USER: ${DB_USER}
   REDIS_HOST: redis-app
   REDIS_HOST_PASSWORD: 9f1297a5793ed18422d3ec92a0eb23d9d91e68d7524937af6248d0ed6b6d006f
  labels:
    - "traefik.enable=true"
    - "traefik.http.middlewares.nextcloud-caldav.redirectregex.permanent=true"
    - "traefik.http.middlewares.nextcloud-caldav.redirectregex.regex=^https://(.*)/.well-known/(card|cal)dav"
    - "traefik.http.middlewares.nextcloud-caldav.redirectregex.replacement=https://$${1}/remote.php/dav/"
    - "traefik.http.middlewares.nextcloud-https.redirectscheme.scheme=https"
    - "traefik.http.routers.nextcloud-http.entrypoints=http"
    - "traefik.http.routers.nextcloud-http.rule=Host(`nextcloud.$DOMAINNAME`)"
    - "traefik.http.routers.nextcloud-http.middlewares=nextcloud-https@docker"
    - "traefik.http.routers.nextcloud.entrypoints=https"
    - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.$DOMAINNAME`)"
    - "traefik.http.routers.nextcloud.middlewares=nextcloud-caldav@docker"
    - "traefik.http.routers.nextcloud.tls=true"
    - "traefik.http.routers.nextcloud.tls.certresolver=default"
  volumes:
   - /media/t1/nextclouddata:/var/www/html/data
   - ${DATADIR}/nextcloud/wwwdata:/var/www/html
  external_links:
   - mariadbmaster
   - redis-app

networks:
  intern:
    external: true
  t2_proxy:
    external: true
##EOF
