version: "3.3"
services:

# Coder
  coder:
    image: linuxserver/code-server
    container_name: coder
    volumes:
      - ${USERDIR}:/home/coder/project
      - ${DATADIR}/coder/config:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PASSWORD=password #optional
      - SUDO_PASSWORD=password #optional
    ports:
      - 8443:8443
    restart: unless-stopped

