version: '3.7'

services:

  gotify:
    container_name: gotify
    image: gotify/server
    restart: always
    networks:
      - t2_proxy
    volumes:
      - ${DATADIR}/gotify/data:/app/data
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.gotify-rtr.entrypoints=https"
      - "traefik.http.routers.gotify-rtr.rule=Host(`gotify.$DOMAINNAME`)"
      - "traefik.http.routers.gotify-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.gotify-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.gotify-rtr.service=gotify-svc"
      - "traefik.http.services.gotify-svc.loadbalancer.server.port=80"
      - flame.type=application # "app" works too
      - flame.name=gotify
      - flame.url=https://gotify.eisvogelweg2.de
      - flame.icon=gotify.png # Optional, default is "docker"

networks:
  t2_proxy:
    external: true



