version: "2.1"

services:
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    command:
      - serve
    environment:
      - TZ=Europe/Berlin # optional: set desired timezone
    #    user: 1000:998 # optional: replace with your own user/group or uid/gid
    volumes:
      - ./cache/ntfy:/var/cache/ntfy
      - ./etc/ntfy:/etc/ntfy
      - ./lib/ntfy:/var/lib/ntfy
        #    ports:
        #      - 39080:80
    restart: unless-stopped
    networks:
      - t2_proxy
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.ntfy-rtr.entrypoints=https"
      - "traefik.http.routers.ntfy-rtr.rule=Host(`ntfy.$DOMAINNAME`)"
      - "traefik.http.routers.ntfy-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.ntfy-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.ntfy-rtr.service=ntfy-svc"
      - "traefik.http.services.ntfy-svc.loadbalancer.server.port=80"
      - "com.centurylinklabs.watchtower.enabled=true"

networks:
  t2_proxy:
    external: true
