
services:

  navidrome:
    container_name: navidrome
    image: deluan/navidrome:latest
    restart: unless-stopped
    ports:
      - "4533:4533"
    networks:
      - t2_proxy
    volumes:
      - /mnt/nasgard/Medien/Music/Musik:/music/albums:ro
      - /mnt/nasgard/Medien/Music/Various:/music/sampler:ro
      - ${DATADIR}/navidrome/data:/data
    environment:
      - ND_SCANSCHEDULE=1h
      - ND_LOGLEVEL=info
      - ND_ENABLEGRAVATAR=true
      - ND_DEFAULTLANGUAGE="de"
      - ND_LASTFM_ENABLED=true
      - ND_LASTFM_LANGUAGE="de"
      - ND_LASTFM_APIKEY=$ND_LASTFM_APIKEY
      - ND_LASTFM_SECRET=$ND_LASTFM_SECRET
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.navidrome-rtr.entrypoints=https"
      - "traefik.http.routers.navidrome-rtr.rule=Host(`navidrome.$DOMAINNAME`)"
      - "traefik.http.routers.navidrome-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.navidrome-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.navidrome-rtr.service=navidrome-svc"
      - "traefik.http.services.navidrome-svc.loadbalancer.server.port=4533"
      - flame.type=application # "app" works too
      - flame.name=navidrome
      - flame.url=https://navidrome.eisvogelweg2.de
      - flame.icon=search-web # Optional, default is "docker"

  bonob:
    image: simojenki/bonob:latest
    user: 1000:1000 # should be owner of volumes
    ports:
      - "4534:4534"
    restart: unless-stopped
    environment:
      BNB_PORT: 4534
      # ip address of your machine running bonob
      BNB_URL: http://192.168.2.22:4534
      BNB_SECRET: "$BNB_SECRET"
      BNB_SONOS_AUTO_REGISTER: "true"
      BNB_SONOS_DEVICE_DISCOVERY: "true"
      BNB_SONOS_SERVICE_ID: 246
      # ip address of one of your sonos devices
      BNB_SONOS_SEED_HOST: 192.168.2.161
      BNB_SUBSONIC_URL: http://navidrome:4533
    networks:
      - t2_proxy


networks:
  t2_proxy:
    external: true
