version: "2.1"
services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - ${DATADIR}/mosquitto/config:/mosquitto/config
      - ${DATADIR}/mosquitto/data:/mosquitto/data
      - ${DATADIR}/mosquitto/log:/mosquitto/log
    expose:
      - 8883
      - 9001
    networks:
      - t2_proxy
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=t2_proxy"
      - "traefik.http.routers.mqtt.rule=Host(`mqtt.eisvogelweg2.de`)"
      - "traefik.http.routers.mqtt.entrypoints=https"
      - "traefik.http.routers.mqtt.tls.certresolver=default"
      - "traefik.tcp.routers.mqtt.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.mqtt.tls.certresolver=default"
      - "traefik.tcp.services.mqtt.loadbalancer.server.port=8883"
      - "traefik.tcp.routers.mqtt.entrypoints=mqtt"
      - "traefik.http.services.mqtt.loadbalancer.server.port=9001"

        #      - "traefik.tcp.routers.tcpr_mqtt_websocket.entrypoints=websocket"
        #      - "traefik.tcp.routers.tcpr_mqtt_websocket.rule=HostSNI(`mqtt.eisvogelweg2.de`)"
        #      - "traefik.tcp.routers.tcpr_mqtt_websocket.service=mqtt_websocket"
        #      - "traefik.tcp.services.mqtt_websocket.loadbalancer.server.port=9001"

networks:
  t2_proxy:
    external: true

