version: '3.3'
services:
  nextcloud-db:
    image: mariadb:10.5
    container_name: nextcloud-db
    command: --transaction-isolation=READ-COMMITTED --log-bin=ROW
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ${DATADIR}/nextcloud/database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${NC_MYSQL_ROOT_PASSORD} #SQL root Passwort eingeben
      - MYSQL_PASSWORD=${NC_MYSQL_PASSWORD} #SQL Benutzer Passwort eingeben
      - MYSQL_DATABASE=${NC_MYSQL_DATABASE} #Datenbank Name
      - MYSQL_USER=${NC_MYSQL_USER} #SQL Nutzername
      - MYSQL_INITDB_SKIP_TZINFO=1
    networks:
      - default

  nextcloud-redis:
    image: redis:alpine
    container_name: nextcloud-redis
    hostname: nextcloud-redis
    networks:
        - default
    restart: unless-stopped
    volumes:
        - /opt/docker-data/nc/redis:/data
    command: redis-server --requirepass test # Redis Passwort eingeben

  nextcloud-app:
    image: nextcloud
    container_name: nextcloud-app
    restart: unless-stopped
    depends_on:
      - nextcloud-redis
      - nextcloud-db
    environment:
        REDIS_HOST: nextcloud-redis
        REDIS_HOST_PASSWORD: test # Redis Passwort von oben wieder eingeben
        NEXTCLOUD_TRUSTED_DOMAINS: nextcloud.${DOMAINNAME}
        TRUSTED_PROXIES: 192.168.90.0/24
    volumes:
      - ${DATADIR}/nextcloud/app:/var/www/html
      - ${DATADIR}/nextcloud/daten:/var/www/html/data
      - ${DATADIR}/nextcloud/daten/external:/var/www/html/data/external
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.nextcloud.middlewares=nextcloud,nextcloud-caldav
      - traefik.http.routers.nextcloud.tls.certresolver=default
      - traefik.http.routers.nextcloud.rule=Host(`nextcloud.${DOMAINNAME}`)
      - traefik.http.middlewares.nextcloud.headers.customFrameOptionsValue=SAMEORIGIN
      - traefik.http.middlewares.nextcloud.headers.contentSecurityPolicy=frame-ancestors 'self' ${DOMAINNAME} *.${DOMAINNAME}
      - traefik.http.middlewares.nextcloud.headers.stsSeconds=155520011
      - traefik.http.middlewares.nextcloud.headers.stsIncludeSubdomains=true
      - traefik.http.middlewares.nextcloud.headers.stsPreload=true
       #      - traefik.http.middlewares.nextcloud_redirect.redirectregex.regex=/.well-known/(card|cal)dav
       #      - traefik.http.middlewares.nextcloud_redirect.redirectregex.replacement=/remote.php/dav/
      - traefik.http.middlewares.nextcloud-caldav.redirectregex.permanent=true
      - traefik.http.middlewares.nextcloud-caldav.redirectregex.regex=^https://(.*)/.well-known/(card|cal)dav
      - traefik.http.middlewares.nextcloud-caldav.redirectregex.replacement=https://$${1}/remote.php/dav/
    networks:
      - t2_proxy
      - default
networks:
  t2_proxy:
    external: true

