---
version: "2.2"
services:
  openhab:
    image: openhab/openhab:latest
    container_name: openhab
    #    ports:
    #      - "9080:8080"
    #      - "9443:8443"
    #      - "9101:8101"
    environment:
      - USER_ID=998
      - GROUP_ID=997
      - TZ=Europe/Berlin
      - OPENHAB_HTTP_PORT=9080
      - OPENHAB_HTTPS_PORT=9443
      - LANG=de_DE.UTF-8
      - LC_ALL=de_DE.UTF-8
      - LANGUAGE=de_DE.UTF-8
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ${DATADIR}/openhab/conf:/openhab/conf
      - ${DATADIR}/openhab/userdata:/openhab/userdata
      - ${DATADIR}/openhab/addons:/openhab/addons
      - ${DATADIR}/openhab/etc:/etc/openhab
    restart: unless-stopped
    network_mode: host
    #networks:
    #  - t2_proxy

    #networks:
    #    t2_proxy:
    #        external: true


