version: "3.5"

services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    volumes:
      - "./data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=Europe/Berlin"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
      - "DIUN_WATCH_WORKERS=20"
      - "DIUN_WATCH_SCHEDULE=0 */6 * * *"
      - "DIUN_PROVIDERS_DOCKER=true"
      - "DIUN_PROVIDERS_DOCKER_WATCHSTOPPED=true"
      - "DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true"
      - "DIUN_NOTIF_MQTT_HOST=192.168.2.22"
      - "DIUN_NOTIF_MQTT_PORT=1883"
      - "DIUN_NOTIF_MQTT_USERNAME=openhabian"
      - "DIUN_NOTIF_MQTT_PASSWORD=ikscrmzziQm3C5"
      - "DIUN_NOTIF_MQTT_CLIENT=diun"
      - "DIUN_NOTIF_MQTT_TOPIC=docker/diun"
      - "DIUN_NOTIF_MQTT_QOS=0"
      - "DIUN_NOTIF_TELEGRAM_TOKEN=777490832:AAGVDsjef3t06aRWDyYSLipsZWVSMn-HEp0"
      - "DIUN_NOTIF_TELEGRAM_CHATIDS=8503256"
    labels:
      - "diun.enable=true"
      - "diun.watch_repo=true"
    restart: always

