version: "3.3"
services:

# Watchtower for automatic updates
  watchtower:
    container_name: watchtower
    restart: always
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 600 --cleanup
    environment:
      -WATCHTOWER_NOTIFICATIONS=email
      -WATCHTOWER_NOTIFICATION_EMAIL_FROM=eddie.faf@gmail.com
      -WATCHTOWER_NOTIFICATION_EMAIL_TO=eddie.faf@gmail.com
      -WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.gmail.com
      -WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=eddie.faf@gmail.com
      -WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=ahvsqakkrewzxqby

networks:
  default:
    external:
      name: nginx-proxy
  default:
    driver: bridge

