---
version: "2"
services:
  mayan:
    image: mayanedms/mayanedms:latest
    container_name: mayan-edms
    environment:
      - MAYAN_DATABASE_ENGINE=django.db.backends.postgresql
      - MAYAN_DATABASE_HOST=mayan-edms-postgres
      - MAYAN_DATABASE_NAME=mayan
      - MAYAN_DATABASE_PASSWORD=mayansecret
      - MAYAN_DATABASE_USER=mayan
      - MAYAN_DATABASE_CONN_MAX_AGE=0
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DATADIR}/mayan-edms/media:/var/lib/mayan
      - /mnt/nasgard/incoming/mayan-edms/staging:/staging_files
      - /mnt/nasgard/incoming/mayan-edms/watching:/watching_files
    ports:
      - 81:8000
    restart: unless-stopped

  mayan-edms-postgres:
    image: postgres:9.6
    container_name: mayan-edms-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=mayan
      - POSTGRES_DB=mayan
      - POSTGRES_PASSWORD=mayansecret
    volumes:
      - /home/eddie/docker-data/mayan-edms/postgres:/var/lib/postgresql/data

networks:
  default:
    external:
      name: mayan



