version: "3"
services:
  bitwarden:
    image: mprasil/bitwarden
    container_name: bitwarden
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATADIR}/bitwarden/data:/data/:rw
    environment:
      - VIRTUAL_HOST=bitwarden.${DOMAINNAME}
      - LETSENCRYPT_HOST=bitwarden.${DOMAINNAME}
      - LETSENCRYPT_EMAIL=eddie.faf@googlemail.com
      - SIGNUPS_ALLOWED=true
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - LOG_FILE=${DATADIR}/bitwarden/bitwarden.log

networks:
  default:
    external: 
      name: nginx-proxy

