version: '3'

services:
    ftpd_server:
        image: stilliard/pure-ftpd
        container_name: pure-ftpd
        ports:
            - "21:21"
            - "30000-30009:30000-30009"
        volumes:
            - "/mnt/nasgard/Import/scanner:/home/scanner"
            - "/opt/docker-data/pure-ftpd/passwd:/etc/pure-ftpd/passwd"
            - "/opt/docker-data/pure-ftpd/users:/home/ftpusers"
        environment:
            PUBLICHOST: "192.168.2.22"
            FTP_USER_NAME: scanner
            FTP_USER_PASS: nextcloud
            FTP_USER_HOME: /home/scanner
        restart: always

