version: "3.3"
services:

# Monitorr
  monitorr:
    image: monitorr/monitorr
    container_name: monitorr
    restart: on-failure
    expose:
      - 80
    volumes:
      - ${DATADIR}/monitorr/app:/app
      - ${DATADIR}/monitorr/config:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VIRTUAL_HOST=monitorr.${DOMAINNAME}
      - LETSENCRYPT_HOST=monitorr.${DOMAINNAME}
      - LETSENCRYPT_EMAIL=eddie.faf@googlemail.com

networks:
  default:
    external:
      name: nginx-proxy

