### phpMyAdmin
### docker-compose.yml
###
##START
version: '3'
services:
  phpmyadmin:
    image: iwfwebsolutions/phpmyadmin-portainer:latest
    restart: "unless-stopped"
    container_name: phpmyadmin
    networks:
      - t2_proxy
    ports:
      - 80
    environment:
    #   PMA_HOST: mariadbmaster
      - PMA_ARBITRARY=1
      - PMA_ABSOLUTE_URI=https://phpmyadmin.eisvogelweg2.de
      - PORTAINER_URL=https://portainer.eisvogelweg2.de
      - PORTAINER_USER=eddie
      - PORTAINER_PASS=ilikec0derz!
      - PORTAINER_NETWORK=t2_proxy
    labels:
      - "traefik.enable=true"
     ## HTTP Routers
      - "traefik.http.routers.phpmyadmin-rtr.entrypoints=https"
      - "traefik.http.routers.phpmyadmin-rtr.rule=Host(`phpmyadmin.$DOMAINNAME`)"
      - "traefik.http.routers.phpmyadmin-rtr.tls=true"
#   - "traefik.http.routers.phpmyadmin-rtr.tls.certresolver=dns-cloudflare"
   ## Middlewares
#   - "traefik.http.routers.phpmyadmin-rtr.middlewares=chain-no-auth@file" # No Authentication
#   - "traefik.http.routers.phpmyadmin-rtr.middlewares=chain-basic-auth@file" # Basic Authentication
      - "traefik.http.routers.phpmyadmin-rtr.middlewares=chain-authelia@file" # Google OAuth 2.0
   ## HTTP Services
      - "traefik.http.routers.phpmyadmin-rtr.service=phpmyadmin-svc"
      - "traefik.http.services.phpmyadmin-svc.loadbalancer.server.port=80"
      - flame.type=application # "app" works too
      - flame.name=phpmyadminn
      - flame.url=https://phpmyadmin.eisvogelweg2.de
      - flame.icon=phpmyadmin.png # Optional, default is "docker"
    volumes:
      - ./sessions:/sessions
      #  external_links:
    #   - mariadbmaster
networks:
  t2_proxy:
    external: true
##EOF

