version: "3"
services:
  bitwarden:
    image: bitwardenrs/server:latest
    container_name: bitwarden
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATADIR}/bitwarden/data:/data/:rw
    environment:
      - SIGNUPS_ALLOWED=true
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - LOG_FILE=/data/bitwarden.log
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bitwarden.entrypoints=http"
      - "traefik.http.routers.bitwarden.rule=Host(`bitwarden.eisvogelweg2.de`)"
      - "traefik.http.routers.bitwarden.middlewares=https-redirect@file"
      - "traefik.http.routers.bitwarden-sec.entrypoints=https"
      - "traefik.http.routers.bitwarden-sec.middlewares=default-headers@file"
      - "traefik.http.routers.bitwarden-sec.rule=Host(`bitwarden.eisvogelweg2.de`)"
      - "traefik.http.routers.bitwarden-sec.tls=true"
      - "traefik.http.routers.bitwarden-sec.tls.options=myTLSOptions@file"
      - "traefik.http.routers.bitwarden-sec.tls.certresolver=le"
      - "traefik.http.services.bitwarden.loadbalancer.server.port=80"

networks:
  web:
    external: true

