version: "3"
services:
  bitwarden:
    image: mprasil/bitwarden
    container_name: bitwarden
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATADIR}/bitwarden/data:/data/:rw
    environment:
      - SIGNUPS_ALLOWED=true
      - ADMIN_TOKEN=${ADMIN_TOKEN}
    networks:
      - traefik_proxy
    labels:
      - traefik.enable=true
      - traefik.backend=bitwarden
      - traefik.frontend.rule=Host:bitwarden.${DOMAINNAME}

networks:
  traefik_proxy:
    external: 
      name: traefik_proxy

