version: "3.3"
services:

  wordpress-app:
    image: wordpress:latest
    container_name: wordpress-app
    restart: always
    links:
    - wordpress-db
    environment:
      - WORDPRESS_DB_HOST=wordpress-db
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=terror
      - ZABBIX_HOSTNAME=wordpress-app
      - VIRTUAL_HOST=blog.eisvogelweg2.de
      - LETSENCRYPT_HOST=blog.eisvogelweg2.de
      - LETSENCRYPT_EMAIL=eddie.faf@goooglemail.com
    volumes:
      - ${USERDIR}/docker/wordpress/data:/var/www/html
      - ${USERDIR}/docker/wordpress/logs/:/www/logs
    expose:
      - 80

  wordpress-db:
    image: tiredofit/mariadb
    container_name: wordpress-db
    restart: always
    volumes:
      - ${USERDIR}/docker/wordpress/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=wordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_PASSWORD=terror
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - ZABBIX_HOSTNAME=wordpress-db

  wordpress-db-backup:
    container_name: wordpress-db-backup
    image: tiredofit/mariadb-backup
    restart: always
    links:
     - wordpress-db
    volumes:
      - ${USERDIR}/docker/wordpress/dbbackups:/backups
    environment:
      - DB_SERVER=wordpress-db
      - DB_TYPE=mysql
      - DB_NAME=wordpress
      - DB_USER=wordpress
      - DB_PASSWORD=terror
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=0000
      - DB_CLEANUP_TIME=8640
      - COMPRESSION=BZ
      - SPLIT_DB=FALSE

networks:
  default:
    external:
      name: nginx-proxy

