version: "3.3"
services:

  clarkson-app:
    image: lsiodev/clarkson
    container_name: clarkson
    restart: always
    links:
    - clarkson-db
    environment:
      - PUID={PUID}
      - PGID={PGID}
      - TZ={TZ}
      - MYSQL_HOST=clarkson-db
      - MYSQL_USERNAME=clarkson
      - MYSQL_PASSWORD=${CLARKSON_PASSWORD}
      - ENABLE_REGISTRATIONS=false
    volumes:
      - ${DATADIR}/clarkson/data:/var/www/html
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.clarkson-rtr.entrypoints=https"
      - "traefik.http.routers.clarkson-rtr.rule=Host(`tanken.$DOMAINNAME`)"
      - "traefik.http.routers.clarkson-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.clarkson-rtr.middlewares=chain-no-auth@file" # No Authentication
#      - "traefik.http.routers.clarkson-rtr.middlewares=chain-basic-auth@file" # Basic Authentication
#      - "traefik.http.routers.clarkson-rtr.middlewares=chain-oauth@file" # Google OAuth 2.0
      ## HTTP Services
      - "traefik.http.routers.clarkson-rtr.service=clarkson-svc"
      - "traefik.http.services.clarkson-svc.loadbalancer.server.port=3000"
#    ports:
#      - 3001:3000
    networks:
      - t2_proxy

  clarkson-db:
    image: tiredofit/mariadb
    container_name: clarkson-db
    restart: always
    volumes:
      - ${DATADIR}/clarkson/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=clarkson
      - MYSQL_DATABASE=clarkson
      - MYSQL_PASSWORD=${CLARKSON_PASSWORD}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - t2_proxy

networks:
  t2_proxy:
    external: true


