version: "3.3"
services:

  clarkson-app:
    image: lsiodev/clarkson
    container_name: clarkson
    restart: always
    links:
    - clarkson-db
    environment:
      - PUID={PUID}
      - PGID={PGID}
      - TZ={TZ}
      - MYSQL_HOST=clarkson-db
      - MYSQL_USERNAME=clarkson
      - MYSQL_PASSWORD=${CLARKSON_PASSWORD}
      - ENABLE_REGISTRATIONS=true
    volumes:
      - ${DATADIR}/clarkson/data:/var/www/html
#      - ${DATADIR}/wordpress/logs/:/www/logs
    ports:
      - 3000:3000
    networks:
      - t2_proxy

  clarkson-db:
    image: tiredofit/mariadb
    container_name: clarkson-db
    restart: always
    volumes:
      - ${DATADIR}/clarkson/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=clarkson
      - MYSQL_DATABASE=clarkson
      - MYSQL_PASSWORD=${CLARKSON_PASSWORD}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - t2_proxy

networks:
  t2_proxy:
    external: true


