---
version: "2"
services:
  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    networks:
      - traefik_proxy
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DATADIR}/jellyfin/config:/config
      - /mnt/tvshows:/data/tvshows
      - /mnt/movies:/data/movies
      - /mnt/anime/series:/data/tvshows2
      - /mnt/anime/movies:/data/movies2
      - ${DATADIR}/jellyfin/transcoding:/transcode #optional
    labels:
      - traefik.enable=false
    ports:
      - 8096:8096
      - 8920:8920 #optional
    devices:
      - /dev/dri:/dev/dri #optional

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
