---
version: "3.3"

services:
  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    networks:
      - traefik_proxy
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DATADIR}/jellyfin/config:/config
      - /mnt/tvshows:/data/tvshows
      - /mnt/movies:/data/movies
      - /mnt/anime/series:/data/tvshows2
      - /mnt/anime/movies:/data/movies2
      - /mnt/music:/data/music
      - ${DATADIR}/jellyfin/transcoding:/transcode #optional
    labels:
      - traefik.enable=false
    ports:
      - 8096:8096
      - 8920:8920 #optional
    devices:
      - /dev/dri:/dev/dri #optional
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8096 || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 5

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
