version: "3.3"
services:

# NGINX as Webserver for www.eisvogelweg2.de
  nginx:
    container_name: www.eisvogelweg2.de
    restart: unless-stopped
    image: linuxserver/nginx
    volumes:
      - ${DATADIR}/www.eisvogelweg2.de/config:/config
#    ports:
#      - 50080:80
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - t2_proxy
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.eisvogelweg2-rtr.entrypoints=https"
      - "traefik.http.routers.eisvogelweg2-rtr.rule=Host(`www.$DOMAINNAME`)"
      - "traefik.http.routers.eisvogelweg2-rtr.tls=true"
#      - "traefik.http.routers.portainer-rtr.tls.certresolver=dns-cloudflare"
      ## Middlewares
      - "traefik.http.routers.eisvogelweg2-rtr.middlewares=chain-no-auth@file" # No Authentication
#      - "traefik.http.routers.portainer-rtr.middlewares=chain-basic-auth@file" # Basic Authentication
#      - "traefik.http.routers.portainer-rtr.middlewares=chain-oauth@file" # Google OAuth 2.0
      ## HTTP Services
      - "traefik.http.routers.eisvogelweg2-rtr.service=eisvogelweg2-svc"
      - "traefik.http.services.eisvogelweg2-svc.loadbalancer.server.port=80"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://www.eisvogelweg2.de || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 5

networks:
  t2_proxy:
    external: true
