version: '3.5' 
services:

  nginx:
    image: jwilder/nginx-proxy
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${DATADIR}/proxy/conf.d:/etc/nginx/conf.d
      - ${DATADIR}/proxy/vhost.d:/etc/nginx/vhost.d
      - ${DATADIR}/proxy/html:/usr/share/nginx/html
      - ${DATADIR}/shared/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ${DATADIR}/shared/htpasswd:/etc/nginx/htpasswd
      - ${DATADIR}/proxy/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - ${DATADIR}/proxy/dhparam:/etc/nginx/dhparam
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
      - "com.ouroboros.enable=true"

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: unless-stopped
    volumes:
      - ${DATADIR}/proxy/conf.d:/etc/nginx/conf.d
      - ${DATADIR}/proxy/vhost.d:/etc/nginx/vhost.d
      - ${DATADIR}/proxy/html:/usr/share/nginx/html
      - ${DATADIR}/shared/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "com.ouroboros.enable=true"

# DDNS updates at Cloudflare
  cloudflare-ddns:
    container_name: cloudflare-ddns
    hostname: cloudflare
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - EMAIL=eddie.faf@googlemail.com
      - API_KEY=${API_KEY_1}
      - ZONE=eisvogelweg2.de
      - PROXIED=false
    labels:
      - "com.ouroboros.enable=true"

# DDNS updates at Cloudflare
  cloudflare-ddns-2:
    container_name: cloudflare-ddns-2
    hostname: cloudflare
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - EMAIL=eddie.faf@googlemail.com
      - API_KEY=${API_KEY_2}
      - ZONE=honkhausen.de
      - PROXIED=false
    labels:
      - "com.ouroboros.enable=true"

# Updater ouroboros
  auto-updater:
    image: pyouroboros/ouroboros:latest
    container_name: ouroboros
    restart: unless-stopped
    environment:
      - CLEANUP=true #delete old images after update
      - DOCKER_SOCKETS="unix://var/run/docker.sock" #comment this line out on windows
      - INTERVAL=300
      - LOG_LEVEL=info
      - SELF_UPDATE=true
      #get auto-update config from labels and only labels.  If a container is not labeled to auto update, don't autoupdate
      - LABEL_ENABLE=true
      - LABELS_ONLY=true
      - TZ=${TZ}
      - CRON="*/30 * * * *"
      - NOTIFIERS=${TGRAM}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock ###Comment this line out in Windows
    labels:
      - "com.ouroboros.enable=true"

  portainer:
    image: portainer/portainer:latest
    ports:
      #by mapping this port to the host, we are also making this service available even if
      #traefik is not running at http://localhost:9000 on your host pc or
      #http://yourhostPCsnetworkname:9000 from other PCs on your network
      #note that it is an insecure http connection.  Comment out the ports section if
      #you do not trust the other devices on your network to not spy on you
      - "9000:9000"
#    expose:
#      - "9000"
    container_name: portainer
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VIRTUAL_HOST=portainer.${DOMAINNAME}
      - VIRTUAL_PORT=9000
      - LETSENCRYPT_HOST=portainer.${DOMAINNAME}
      - LETSENCRYPT_EMAIL=eddie.faf@googlemail.com
    labels:
      - com.ouroboros.enable=true
    volumes:
      - ${DATADIR}/portainer/data:/data #map named volume to directory in container
      #allows portainer to control docker (Linux/Mac only)
      - /var/run/docker.sock:/var/run/docker.sock ###Comment this line out in Windows
    #this section allows us to modify arguments passed to the default command executed inside this container (AKA the entrypoint)
    #when it starts
###    command: -d /data -H npipe:////./pipe/docker_engine #uncomment this line in windows
###    command: -d /data -H tcp://localhost:2375 #alternative to the last line, pick only 1!
    restart: unless-stopped

networks:
  default:
    external:
      name: nginx-proxy

