version: '3' 
services:

  nginx:
    image: nginx
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${DATADIR}/proxy/conf.d:/etc/nginx/conf.d
      - ${DATADIR}/proxy/vhost.d:/etc/nginx/vhost.d
      - ${DATADIR}/proxy/html:/usr/share/nginx/html
      - ${DATADIR}/shared/certs:/etc/nginx/certs:ro

  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    restart: unless-stopped
    volumes:
      - ${DATADIR}/proxy/conf.d:/etc/nginx/conf.d
      - ${DATADIR}/proxy/vhost.d:/etc/nginx/vhost.d
      - ${DATADIR}/proxy/html:/usr/share/nginx/html
      - ${DATADIR}/shared/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ${DATADIR}/proxy/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: unless-stopped
    volumes:
      - ${DATADIR}/proxy/conf.d:/etc/nginx/conf.d
      - ${DATADIR}/proxy/vhost.d:/etc/nginx/vhost.d
      - ${DATADIR}/proxy/html:/usr/share/nginx/html
      - ${DATADIR}/shared/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: "nginx-gen"
      NGINX_PROXY_CONTAINER: "nginx" 

# DDNS updates at Cloudflare
  cloudflare-ddns:
    container_name: cloudflare-ddns
    hostname: cloudflare
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - EMAIL=eddie.faf@googlemail.com
      - API_KEY=5a618dc97b8eea46af82f923e84dfa0dac38d
      - ZONE=eisvogelweg2.de
      - PROXIED=false

# DDNS updates at Cloudflare
  cloudflare-ddns-2:
    container_name: cloudflare-ddns-2
    hostname: cloudflare
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - EMAIL=eddie.faf@googlemail.com
      - API_KEY=5a618dc97b8eea46af82f923e84dfa0dac38d
      - ZONE=honkhausen.de
      - PROXIED=false

networks:
  default:
    external:
      name: nginx-proxy

