### MariaDB
### docker-compose.yml
##Start
version: '3.3'
services:

  mariadbmaster:
    image: tiredofit/mariadb:10.7
    restart: always
    container_name: mariadbmaster
    networks:
      t2_proxy:
        ipv4_address: 192.168.90.250
    security_opt:
      - no-new-privileges:true
    ports:
      - 3306:3306
    environment:
      - ROOT_PASS=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_HOST=192.168.2.22
      - DB_NAME=homeassistant
      - MYSQL_DATABASE=homeassistant
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_BACKUP=false
      - DB_BACKUP_DUMP_FREQ=1440
      - DB_BACKUP_DUMP_BEGIN=0000
      - DB_BACKUP_CLEANUP_TIME=8640
      - DB_BACKUP_MD5=true
      - DB_BACKUP_COMPRESSION=GZ
      - DB_BACKUP_SPLIT_DB=false
      - DB_AUTO_UPGRADE=true
    volumes:
      - ${DATADIR}/mariadbmaster/data:/var/lib/mysql
      - ${DATADIR}/mariadbmaster/conf:/etc/mysql/mariadb.conf.d
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro 
        #     - ${DATADIR}/mariadbmaster/dbbackup:/backup

  maria-db-backup:
    container_name: maria-db-backup
    image: tiredofit/db-backup
    restart: always
    links:
      - mariadbmaster
    volumes:
      - ~/backup/homeassistant/db:/backup
      - ./post-script.sh:/assets/custom-scripts/post-script.sh
    environment:
      - DB_TYPE=mariadb
      - DB_HOST=mariadbmaster
      - DB_NAME=homeassistant
      - DB_USER=dbbackup
      - DB_PASS=dbbackup
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=0000
      - DB_CLEANUP_TIME=8640
      - MD5=TRUE
      - COMPRESSION=GZ
      - SPLIT_DB=TRUE
      - CONTAINER_ENABLE_MONITORING=false
    networks:
      - t2_proxy

networks:
  t2_proxy:
    external: true

##EOF
