---
version: "2"
services:
  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Berlin
    volumes:
      - ./config:/config
      - /mnt/tvshows:/data/tvshows
      - /mnt/movies:/data/movies
      - /mnt/anime/series:/data/tvshows2
      - /mnt/anime/movies:/data/movies2
      - ./transcoding:/transcode #optional
    ports:
      - 8096:8096
      - 8920:8920 #optional
    devices:
      - /dev/dri:/dev/dri #optional
    restart: unless-stopped

