---
version: "2.1"
services:
  jellyfin_traefik:
    image: ghcr.io/linuxserver/jellyfin:latest
    container_name: jellyfin_traefik
    networks:
      - t2_proxy
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=<022> #optional
      - JELLYFIN_PublishedServerUrl=jellyfin.eisvogelweg2.de
    volumes:
      - ${DATADIR}/jellyfin:/config
      - /mnt/nasgard/Medien/Serien:/data/tvshows
      - /mnt/nasgard/Medien/Movies:/data/movies
        #- /opt/vc/lib:/opt/vc/lib #optional
      - /mnt/nasgard/Medien/_unsorted/Anime/Filme:/data/animemovies
      - /mnt/nasgard/Medien/_unsorted/Anime/Serien:/data/animeseries
      - /mnt/nasgard/Medien/_unsorted/Comedy:/data/comedy
      - /mnt/nasgard/Medien/_unsorted/Adult/Movies:/data/adultmovies
      - /mnt/nasgard/Medien/_unsorted/Adult/Anime:/data/adultanime
      - /mnt/nasgard/Medien/Music/Musik:/data/musik
      - /mnt/nasgard/Medien/Music/Various:/data/variousmusik
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.jellyfin-rtr.entrypoints=https"
      - "traefik.http.routers.jellyfin-rtr.rule=Host(`jellyfin.$DOMAINNAME`)"
      - "traefik.http.routers.jellyfin-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.jellyfin-rtr.middlewares=chain-no-auth@file" # No Authentication
#      - "traefik.http.routers.jellyfin-rtr.middlewares=chain-authelia@file" # No Authentication
#      - "traefik.http.routers.portainer-rtr.middlewares=chain-basic-auth@file" # Basic Authentication
#      - "traefik.http.routers.portainer-rtr.middlewares=chain-oauth@file" # Google OAuth 2.0
      ## HTTP Services
      - "traefik.http.routers.jellyfin-rtr.service=jellyfin-svc"
      - "traefik.http.services.jellyfin-svc.loadbalancer.server.port=8096"

      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
        #      - 1900:1900/udp #optional
        #    devices:
            #- /dev/dri:/dev/dri #optional
            #- /dev/vcsm:/dev/vcsm #optional
            #- /dev/vchiq:/dev/vchiq #optional
            #- /dev/video10:/dev/video10 #optional
            #- /dev/video11:/dev/video11 #optional
            #- /dev/video12:/dev/video12 #optional
    restart: unless-stopped

networks:
  t2_proxy:
    external: true

