version: "3.3"
services:

# Coder
  coder:
    image: codercom/code-server
    container_name: coder
    command: '--no-auth --allow-http'
    expose:
     - 8443
    volumes:
     - ${USERDIR}/repositories/docker:/home/coder/project
    networks:
      - traefik_proxy
    labels:
      - traefik.enable=true
      - traefik.backend=coder
      - traefik.frontend.rule=Host:coder.${DOMAINNAME}
      - traefik.port=8443

networks:
  traefik_proxy:
    external:
      name: traefik_proxy

