version: "3.3"
services:

# Portainer
  portainer:
    image: "portainer/portainer"
    container_name: portainer
    restart: always
    command: -H unix:///var/run/docker.sock
    expose:
      - 9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATADIR}/portainer/data:/data
      - ${DATADIR}/shared:/shared
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VIRTUAL_HOST=portainer.${DOMAINNAME}
      - VIRTUAL_PORT=9000
      - LETSENCRYPT_HOST=portainer.${DOMAINNAME}
      - LETSENCRYPT_EMAIL=eddie.faf@googlemail.com

networks:
  default:
    external:
      name: nginx-proxy

