version: "3"
services:
  guacamole:
    image: oznu/guacamole
    container_name: guacamole
    restart: unless-stopped
#    ports:
#      - 55555:8080
    expose:
      - 8080
    volumes:
      - ${DATADIR}/guacamole/config:/config
    environment:
      - VIRTUAL_HOST=guacamole.${DOMAINNAME}
      - LETSENCRYPT_HOST=guacamole.${DOMAINNAME}
      - LETSENCRYPT_EMAIL=eddie.faf@googlmail.com
      - VIRTUAL_PORT=8080
#      - SIGNUPS_ALLOWED=true
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://guacamole.eisvogelweg2.de || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 5

networks:
  default:
    external: 
      name: nginx-proxy

