---
version: "2"
services:
  freshrss:
    image: linuxserver/freshrss
    container_name: freshrss
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DATADIR}/freshrss/data:/config
#    ports:
#      - 8001:80
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.freshrss-rtr.entrypoints=https"
      - "traefik.http.routers.freshrss-rtr.rule=Host(`freshrss.$DOMAINNAME`)"
      - "traefik.http.routers.freshrss-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.freshrss-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.freshrss-rtr.service=freshrss-svc"
      - "traefik.http.services.freshrss-svc.loadbalancer.server.port=80"
      - flame.type=application # "app" works too
      - flame.name=freshrss
      - flame.url=https://freshrss.eisvogelweg2.de
      - flame.icon=freshrss.png # Optional, default is "docker"
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - t2_proxy

networks:
  t2_proxy:
    external: true

