version: "3.3"
services:

# Portainer
  portainer:
    image: "portainer/portainer"
    container_name: portainer
    restart: always
    command: -H unix:///var/run/docker.sock
#    ports:
#      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATADIR}/portainer/data:/data
      - ${DATADIR}/shared:/shared
    environment:
      - TZ=${TZ}
    networks:
      - traefik_proxy
    labels:
      - traefik.enable=true
      - traefik.backend=portainer
      - traefik.frontend.rule=Host:portainer.${DOMAINNAME}
#      - "traefik.frontend.rule=Host:${DOMAINNAME}; PathPrefixStrip: /portainer"
      - traefik.port=9000
#      - traefik.docker.network=traefik_proxy
#      - traefik.frontend.headers.SSLRedirect=true
#      - traefik.frontend.headers.STSSeconds=315360000
#      - traefik.frontend.headers.browserXSSFilter=true
#      - traefik.frontend.headers.contentTypeNosniff=true
#      - traefik.frontend.headers.forceSTSHeader=true
#      - traefik.frontend.headers.SSLHost=eisvogelweg2.de
#      - traefik.frontend.headers.STSIncludeSubdomains=true
#      - traefik.frontend.headers.STSPreload=true
#      - traefik.frontend.headers.frameDeny=true

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge

