version: "3.3"
services:

# Coder
  coder:
    image: codercom/code-server
    container_name: coder
    command: '--no-auth --allow-http'
    expose:
     - 8443
    volumes:
     - ${USERDIR}/docker-repo/docker:/home/coder/project
    environment:
      - VIRTUAL_PORT=8443
      - VIRTUAL_HOST=coder.${DOMAINNAME}
      - LETSENCRYPT_HOST=coder.${DOMAINNAME}
      - LETSENCRYPT_EMAIL=eddie.faf@googlemail.com

networks:
  default:
    external:
      name: nginx-proxy

