---
version: "2"
services:
  mstream:
    image: linuxserver/mstream
    container_name: mstream
    restart: unless-stopped
#    expose:
#      - 3000
    ports:
      - 53000:3000
    networks:
      - traefik_proxy
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - USER=admin
      - PASSWORD=password
      - USE_JSON=true
      - TZ=${TZ}
    volumes:
      - ${DATADIR}/mstream/config:/config
      - /mnt/nasgard/Medien/Music:/music
    labels:
      - traefik.enable=true
      - traefik.backend=mstream
      - traefik.frontend.rule=Host:mstream.${DOMAINNAME}
      - traefik.port=3000

networks:
  traefik_proxy:
    external:
      name: traefik_proxy

