---
version: "2.1"
services:
  influxdb:
    image: influxdb:latest
    container_name: "influxdb"
    healthcheck:
      test: ["CMD", "curl", "-sI", "http://127.0.0.1:8086/ping"]
      interval: 30s
      timeout: 1s
      retries: 24
    environment:
      - TZ=${TZ}
    network_mode: host
    ports:
      - 8083:8083
      - 8086:8086
    restart: unless-stopped
    volumes:
      - ${DATADIR}/influxdb:/var/lib/influxdb2
      - ${DATADIR}/influxdb/etc:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=openhabian
      - DOCKER_INFLUXDB_INIT_PASSWORD=ilikec0derz!
      - DOCKER_INFLUXDB_INIT_ORG=eisvogelweg2
      - DOCKER_INFLUXDB_INIT_BUCKET=openhab


