services:
  wg-easy:
    environment:
      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST=vpn.${DOMAINNAME}

      # Optional:
      # - PASSWORD=foobar123
      - WG_PORT=51820
      # - WG_DEFAULT_ADDRESS=10.8.0.x
      - WG_DEFAULT_DNS=192.168.2.30
      - LANG=de
      - UI_CHART_TYPE=1
      - UI_TRAFFIC_STATS=true

    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    volumes:
      - ${DATADIR}/wireguard/config:/etc/wireguard
    labels:
      - flame.type=application # "app" works too
      - flame.name=wireguard
      - flame.url=https://vpn.eisvogelweg2.de
      - flame.icon=wireguard.png # Optional, default is "docker"
      - wud.watch=true
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1

