version: "3.3"
services:

# Systemweiter Ad Blocker
  pihole:
    container_name: pihole
#    domainname: ${DOMAINNAME}
    domainname: fritz.box
    hostname: pihole
    image: pihole/pihole:latest
    dns:
      - 127.0.0.1
      - 1.1.1.1
    ports:
      - '0.0.0.0:53:53/tcp'
      - '0.0.0.0:53:53/udp'
      # - '67:67/udp'
      - '0.0.0.0:8182:80/tcp'
    restart: unless-stopped
    volumes:
      - ${DATADIR}/pihole/pihole:/etc/pihole
      - ${DATADIR}/pihole/pihole.log:/var/log/pihole.log
      - ${DATADIR}/pihole/dnsmasq.d:/etc/dnsmasq.d
    cap_add:
       - NET_ADMIN
    environment:
      - ServerIP=${SERVER_IP}
      - PROXY_LOCATION=pihole
      - VIRTUAL_HOST=pihole.${DOMAINNAME}
      - VIRTUAL_PORT=80
      - TZ=${TZ}
      - WEBPASSWORD=terror
      - DNS1=127.0.0.1
      - DNS2=1.1.1.1
    networks:
      - traefik_proxy
    labels:
      - traefik.enable=true
      - traefik.backend=pihole
      - traefik.port=80
      - traefik.frontend.rule=Host:pihole.${DOMAINNAME}
      - traefik.frontend.priority=1
#      - traefik.frontend.headers.SSLRedirect=true
#      - traefik.frontend.headers.STSSeconds=315360000
#      - traefik.frontend.headers.browserXSSFilter=true
#      - traefik.frontend.headers.contentTypeNosniff=true
#      - traefik.frontend.headers.forceSTSHeader=true
#      - traefik.frontend.headers.SSLHost=${DOMAINNAME}
#      - traefik.frontend.headers.STSIncludeSubdomains=true
#      - traefik.frontend.headers.STSPreload=true
#      - traefik.frontend.headers.frameDeny=true

networks:
  traefik_proxy:
    external:
      name: traefik_proxy

