version: "3.3"
services:

  wordpress-app:
    image: wordpress:latest
    container_name: wordpress-app
    restart: always
    links:
    - wordpress-db
    environment:
      - WORDPRESS_DB_HOST=wordpress-db
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - ZABBIX_HOSTNAME=wordpress-app
    volumes:
      - ${DATADIR}/wordpress/data:/var/www/html
      - ${DATADIR}/wordpress/logs/:/www/logs
    labels:
      - traefik.enable=true
      - traefik.backend=blog
#      - traefik.port=80
      - traefik.frontend.rule=Host:blog.${DOMAINNAME}
    networks:
      - traefik_proxy

  wordpress-db:
    image: tiredofit/mariadb
    container_name: wordpress-db
    restart: always
    volumes:
      - ${DATADIR}/wordpress/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=wordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - ZABBIX_HOSTNAME=wordpress-db
    networks:
      - traefik_proxy

  wordpress-db-backup:
    container_name: wordpress-db-backup
    image: tiredofit/mariadb-backup
    restart: always
    links:
     - wordpress-db
    volumes:
      - ${DATADIR}/wordpress/dbbackups:/backups
    environment:
      - DB_SERVER=wordpress-db
      - DB_TYPE=mysql
      - DB_NAME=wordpress
      - DB_USER=wordpress
      - DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - DB_DUMP_FREQ=1440
      #- DB_DUMP_BEGIN=0000
      - DB_CLEANUP_TIME=8640
      - COMPRESSION=BZ
      - SPLIT_DB=FALSE
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external:
      name: traefik_proxy

