## Coder Image
version: "3.3"
services:

# Coder
  coder:
#    image: linuxserver/code-server
    image: codercom/code-server
    container_name: coder
    networks:
      - t2_proxy
    volumes:
      - /home/eddie/docker/homeassistant/config:/home/coder/project/hass
      - /opt/docker-data/www.honkhausen.de/config/www:/home/coder/project/honkhausen
      - /opt/docker-data/wordpress/app/wp-content:/home/coder/project/wordpress
      - .config:/home/coder/.config
      - .local:/home/coder/.local
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PASSWORD=password #optional
      - SUDO_PASSWORD=password #optional
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.coder-rtr.entrypoints=https"
      - "traefik.http.routers.coder-rtr.rule=Host(`coder.$DOMAINNAME`)"
      - "traefik.http.routers.coder-rtr.tls=true"
      ## Middlewares
#      - "traefik.http.routers.coder-rtr.middlewares=chain-no-auth@file" # No Authentication
      - "traefik.http.routers.coder-rtr.middlewares=chain-authelia@file" # No Authentication
#      - "traefik.http.routers.portainer-rtr.middlewares=chain-basic-auth@file" # Basic Authentication
#      - "traefik.http.routers.portainer-rtr.middlewares=chain-oauth@file" # Google OAuth 2.0
      ## HTTP Services
      - "traefik.http.routers.coder-rtr.service=coder-svc"
      - "traefik.http.services.coder-svc.loadbalancer.server.port=8080"

      - "com.centurylinklabs.watchtower.enable=true"
#    ports:
#      - 8443:8443
    restart: unless-stopped

networks:
  t2_proxy:
    external: true
