---
version: "2"
services:
  calibre:
    image: linuxserver/calibre
    container_name: calibre
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
#      - GUAC_USER=abc #optional
#      - GUAC_PASS=900150983cd24fb0d6963f7d28e17f72 #optional
    volumes:
      - ${DATADIR}/calibre/data:/config
      - "/media/t3/ebooks:/config/Calibre-Bibliothek"
    ports:
      - 8080:8080
      - 8081:8081
    restart: unless-stopped

